### ISSUE TITLE
Fatal Exception (IDE Crash when loading)

### ISSUE THREAD

**Issue by kirillzhosul** [ZeusPlugins/ZplBgMusicPlugin#1]
![Win32ExceptionHandler_CuAqXWUaKM](https://user-images.githubusercontent.com/79853674/123389284-c61edc80-d5aa-11eb-8c05-b1373b01e5ef.png) @nkrapivin 

Fatal exception after loading plugins~ (All working when i disabling MUSIC plugin (there is Discord plugin working)

**Comment by nkrapivin** [comment]
I forgot to publish the layout and csv files :/

**Comment by nkrapivin** [comment]
Try now.

**Comment by kirillzhosul** [comment]
Fixed 👍🏻
